# Generated by Django 5.0.6 on 2024-09-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_id',
        ),
    ]
