# Generated by Django 5.0.6 on 2024-08-30 09:26

import datetime
import django.db.models.deletion
import user_auth.model_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.UUIDField(default='I6Wmz8bR339jsTPDODI07A', null=True, unique=True)),
                ('last_message_date', models.DateTimeField(default=datetime.datetime(2024, 8, 30, 14, 56, 13, 227555))),
                ('room_type', models.CharField(choices=[('one_to_many', 'Group'), ('one_to_one', 'Room')], max_length=20)),
            ],
            bases=(models.Model, user_auth.model_utils.CreatedUpdatedAtModel),
        ),
        migrations.CreateModel(
            name='UnsentMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('user_id', models.IntegerField()),
                ('room_type', models.CharField(choices=[('one_to_many', 'Group'), ('one_to_one', 'Personal')], default='personal', max_length=20)),
                ('room_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('admins', models.ManyToManyField(related_name='admin_groups', to=settings.AUTH_USER_MODEL)),
                ('group_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_profiles', to='user_auth.profilemedia')),
                ('main_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_admin_groups', to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='user_chat.chatroom')),
                ('users', models.ManyToManyField(related_name='group_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, user_auth.model_utils.CreatedUpdatedAtModel),
        ),
        migrations.CreateModel(
            name='PersonalConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('blocked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_list', to=settings.AUTH_USER_MODEL)),
                ('invitee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_rooms', to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='user_chat.chatroom')),
            ],
            bases=(models.Model, user_auth.model_utils.CreatedUpdatedAtModel),
        ),
    ]
