# Generated by Django 5.0.6 on 2024-08-30 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 14, 57, 40, 329206)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.UUIDField(default='Avv5v9LqEUgNeAUj56MM9Q', null=True, unique=True),
        ),
    ]
