# Generated by Django 5.0.6 on 2024-08-30 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0002_alter_chatroom_last_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 14, 57, 47, 275954)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.UUIDField(default='JVZww9xV8uOaUejbTzqaSw', null=True, unique=True),
        ),
    ]
