# Generated by Django 5.0.6 on 2024-08-30 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0003_alter_chatroom_last_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 14, 59, 42, 736459)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.UUIDField(default='mPxKwxgYe0LFaKCO8l06fA', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('one_to_many', 'Group'), ('one_to_one', 'Personal')], max_length=20),
        ),
    ]
