# Generated by Django 5.0.6 on 2024-08-30 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0004_alter_chatroom_last_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 15, 0, 24, 676319)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='baIDsDzhxVEb7DVoKlyq-g', max_length=255, null=True, unique=True),
        ),
    ]
