# Generated by Django 5.0.6 on 2024-08-30 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0006_alter_chatroom_last_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 15, 1, 36, 646257)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='DQIvHsTMsUgif8um0Ck9rg', editable=False, max_length=22, unique=True),
        ),
    ]
