# Generated by Django 5.0.6 on 2024-09-04 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0007_alter_chatroom_last_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 13, 16, 9, 511734)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='KoifPygJhjfTz0ORKvy_ZA', editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='unsentmessages',
            name='room_id',
            field=models.CharField(verbose_name=255),
        ),
    ]
