# Generated by Django 5.0.6 on 2024-09-04 08:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('user_chat', '0009_alter_chatroom_last_message_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupconf',
            name='group_image',
        ),
        migrations.AddField(
            model_name='groupconf',
            name='group_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_profile', to='user_auth.profilemedia'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='last_message_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 13, 48, 33, 61915)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='I2xzn9xXGwgSK48pe9GnjQ', editable=False, max_length=22, unique=True),
        ),
    ]
