# Generated by Django 5.0.6 on 2024-09-04 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0010_remove_groupconf_group_image_groupconf_group_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 14, 30, 44, 47451)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='_eqoLhlCgIObaSTDoHftCg', editable=False, max_length=22, unique=True),
        ),
    ]
