# Generated by Django 5.0.6 on 2024-09-12 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0013_alter_chatroom_last_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 16, 1, 51, 702084)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='1kSjkqZ6oD_2VQu263FlkQ', editable=False, max_length=22, unique=True),
        ),
    ]
