# Generated by Django 5.0.6 on 2024-09-12 10:51

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0014_alter_chatroom_last_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 16, 21, 33, 349)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='J4IWDbQ3QVOOmblcqnlS7A', editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='groupconf',
            name='group_profile',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
