# Generated by Django 5.0.6 on 2024-09-12 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0015_alter_chatroom_last_message_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='last_message_date',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='_last_message_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 16, 45, 11, 190813)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='Kf5JNttF_X3zbcF9ndrsIg', editable=False, max_length=22, unique=True),
        ),
    ]
