# Generated by Django 5.0.6 on 2024-09-16 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0016_remove_chatroom_last_message_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsentmessages',
            name='user_id',
        ),
        migrations.AddField(
            model_name='unsentmessages',
            name='senter',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='_last_message_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='SD-ONF-_L3t195tNi8B00w', editable=False, max_length=22, unique=True),
        ),
    ]
