# Generated by Django 5.0.6 on 2024-09-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0017_remove_unsentmessages_user_id_unsentmessages_senter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unsentmessages',
            old_name='senter',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='EmFHNeM2q79gowaIApOSNw', editable=False, max_length=22, unique=True),
        ),
    ]
